# Generated by Django 3.2.3 on 2021-05-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0002_auto_20210518_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossCuttingIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'cross_cutting_issues',
            },
        ),
        migrations.CreateModel(
            name='NSEDPOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'nsedp_outcomes',
            },
        ),
        migrations.CreateModel(
            name='NSEDPOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'nsedp_outputs',
            },
        ),
        migrations.CreateModel(
            name='SustainableDevelopmentGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'sustainable_development_goals',
            },
        ),
        migrations.DeleteModel(
            name='SDG',
        ),
        migrations.AlterField(
            model_name='sector',
            name='sdg',
            field=models.ManyToManyField(related_name='sustainable_development_goals', to='jplaos.SustainableDevelopmentGoal'),
        ),
    ]
