# Generated by Django 3.2.3 on 2021-05-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0003_auto_20210519_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsedpoutput',
            name='outcome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='jplaos.nsedpoutcome'),
            preserve_default=False,
        ),
    ]
