# Generated by Django 3.2.3 on 2021-05-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0004_nsedpoutput_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cross_cutting_issues',
            field=models.ManyToManyField(blank=True, to='jplaos.CrossCuttingIssue'),
        ),
    ]
