# Generated by Django 3.2.3 on 2021-05-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0005_project_cross_cutting_issues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priorityarea',
            name='sector',
        ),
        migrations.AddField(
            model_name='sector',
            name='priority_area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sectorm', to='jplaos.priorityarea'),
            preserve_default=False,
        ),
    ]
