# Generated by Django 3.2.3 on 2021-06-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0006_auto_20210521_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='outputs',
            field=models.ManyToManyField(related_name='sectors', to='jplaos.NSEDPOutput'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='priority_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='jplaos.priorityarea'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='sdg',
            field=models.ManyToManyField(related_name='sectors', to='jplaos.SustainableDevelopmentGoal'),
        ),
    ]
