# Generated by Django 3.2.3 on 2021-06-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0008_auto_20210611_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='sustainabledevelopmentgoal',
            name='short_name',
            field=models.CharField(default='SDG 1', max_length=10),
            preserve_default=False,
        ),
    ]
