# Generated by Django 3.2.3 on 2021-07-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0010_greencategory_greensubcategory_greensubcategoryfundingallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='green_category_allocation',
            field=models.ManyToManyField(blank=True, to='jplaos.GreenSubCategoryFundingAllocation'),
        ),
    ]
