# Generated by Django 3.2.3 on 2021-07-02 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0011_project_green_category_allocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='green_category_allocation',
        ),
        migrations.AddField(
            model_name='greensubcategoryfundingallocation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='green_categories_funding', to='jplaos.project'),
        ),
    ]
