# Generated by Django 3.2.3 on 2021-08-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0014_auto_20210810_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planed_amount', models.FloatField()),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner',
                                              to='jplaos.partner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jplaos.project')),
            ],
        ),
    ]
