# Generated by Django 3.2.3 on 2021-08-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0015_partnerfunding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplementingPartnerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'implementing_partner_categories',
            },
        )
    ]
