# Generated by Django 3.2.3 on 2021-08-19 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0016_auto_20210819_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementingpartner',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='jplaos.implementingpartnercategory'),
            preserve_default=False,
        ),
    ]
