# Generated by Django 3.2.3 on 2021-08-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0019_auto_20210819_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_regional',
            field=models.BooleanField(default=False),
        ),
    ]
