# Generated by Django 3.2.3 on 2021-08-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0022_fundingbymodality_modality'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementaryAreaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_category', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'complementary_area_categories',
            },
        ),
        migrations.CreateModel(
            name='ForestPartnershipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_category', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'forest_partnership_categories',
            },
        ),
        migrations.CreateModel(
            name='GreenCatalysersCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_category', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'green_catalysers_categories',
            },
        ),
        migrations.CreateModel(
            name='PhakhaoLaoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_category', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'phakhao_lao_categories',
            },
        ),
    ]
