# Generated by Django 3.2.3 on 2021-08-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos',
         '0023_complementaryareacategory_forestpartnershipcategory_greencatalyserscategory_phakhaolaocategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='complementary_area_categories',
            field=models.ManyToManyField(blank=True, to='jplaos.ComplementaryAreaCategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='green_catalysers_categories',
            field=models.ManyToManyField(blank=True, to='jplaos.GreenCatalysersCategory'),
        ),
    ]
