# Generated by Django 3.2.3 on 2021-08-20 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0024_auto_20210820_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingByPhakhaoLaoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding',
                                               to='jplaos.phakhaolaocategory')),
                ('project',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_by_phakhao_lao',
                                   to='jplaos.project')),
            ],
        ),
        migrations.CreateModel(
            name='FundingByForestPartnershipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.IntegerField()),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding',
                                               to='jplaos.forestpartnershipcategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='funding_by_forest_partnership', to='jplaos.project')),
            ],
        ),
    ]
