# Generated by Django 3.2.3 on 2021-08-20 14:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0025_fundingbyforestpartnershipcategory_fundingbyphakhaolaocategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundingbymodality',
            old_name='modality',
            new_name='category',
        ),
    ]
