# Generated by Django 3.2.3 on 2021-08-20 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0026_rename_modality_fundingbymodality_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundingbyforestpartnershipcategory',
            old_name='modality',
            new_name='category',
        ),
    ]
