# Generated by Django 3.2.3 on 2021-08-20 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0027_rename_modality_fundingbyforestpartnershipcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundingbymodality',
            old_name='category',
            new_name='modality',
        ),
    ]
