# Generated by Django 3.2.3 on 2021-08-21 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0028_rename_category_fundingbymodality_modality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='sector',
        ),
    ]
