# Generated by Django 3.2.3 on 2021-08-21 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0029_remove_pipeline_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelineplannedamount',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='pipelines_by_sector', to='jplaos.partner'),
        ),
        migrations.AlterField(
            model_name='pipelineplannedamount',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='pipeline_by_partners', to='jplaos.sector'),
        ),
    ]
