# Generated by Django 3.2.3 on 2021-08-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0030_auto_20210821_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GreenCatalysersCategory',
            new_name='GreenCatalyzersCategory',
        ),
        migrations.RemoveField(
            model_name='project',
            name='green_catalysers_categories',
        ),
        migrations.AddField(
            model_name='project',
            name='green_catalyzers_categories',
            field=models.ManyToManyField(blank=True, to='jplaos.GreenCatalyzersCategory'),
        ),
        migrations.AlterModelTable(
            name='greencatalyzerscategory',
            table='green_catalyzers_categories',
        ),
    ]
