# Generated by Django 3.2.3 on 2021-08-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0031_auto_20210825_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subsector',
        ),
        migrations.AlterModelOptions(
            name='complementaryareacategory',
            options={'verbose_name_plural': 'Complementary Areas'},
        ),
        migrations.AlterModelOptions(
            name='forestpartnershipcategory',
            options={'verbose_name_plural': 'Forest Partnership Categories'},
        ),
        migrations.AlterModelOptions(
            name='fundingbyforestpartnershipcategory',
            options={'verbose_name': 'Forest Partnership', 'verbose_name_plural': 'Forest Partnership'},
        ),
        migrations.AlterModelOptions(
            name='fundingbymodality',
            options={'verbose_name': 'Funding Modality', 'verbose_name_plural': 'Funding Modality'},
        ),
        migrations.AlterModelOptions(
            name='fundingbyphakhaolaocategory',
            options={'verbose_name': 'Phakhao Lao', 'verbose_name_plural': 'Phakhao Lao'},
        ),
        migrations.AlterModelOptions(
            name='greencatalyzerscategory',
            options={'verbose_name_plural': 'Green Catalyzers'},
        ),
        migrations.AlterModelOptions(
            name='modality',
            options={'verbose_name_plural': 'Modality'},
        ),
        migrations.AlterModelOptions(
            name='partnerfunding',
            options={'verbose_name': 'Funding by Partner', 'verbose_name_plural': 'Funding by Partner'},
        ),
        migrations.AlterModelOptions(
            name='phakhaolaocategory',
            options={'verbose_name_plural': 'Phakhao Lao Categories'},
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
