# Generated by Django 3.2.3 on 2021-08-25 22:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0032_auto_20210825_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forestpartnershipcategory',
            options={'verbose_name_plural': 'Forest Partnership'},
        ),
        migrations.AlterModelOptions(
            name='phakhaolaocategory',
            options={'verbose_name_plural': 'Phakhao Lao'},
        ),
    ]
