# Generated by Django 3.2.3 on 2021-08-30 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0033_auto_20210825_2216'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='greencategory',
            table='green_categories',
        ),
    ]
