# Generated by Django 3.2.3 on 2021-08-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0034_alter_greencategory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='implementing_partner_categories',
            field=models.ManyToManyField(to='jplaos.ImplementingPartnerCategory'),
        ),
    ]
