# Generated by Django 3.2.3 on 2021-08-30 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0035_project_implementing_partner_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='implementing_partner',
        ),
        migrations.DeleteModel(
            name='ImplementingPartner',
        ),
    ]
