# Generated by Django 3.2.3 on 2021-08-30 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0036_auto_20210830_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingByGreenCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding',
                                               to='jplaos.greencategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='funding_by_green_category', to='jplaos.project')),
            ],
            options={
                'verbose_name': 'Funding by Green Category',
                'verbose_name_plural': 'Funding by Green Category',
            },
        ),
    ]
