# Generated by Django 3.2.3 on 2021-09-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0039_partneruser_partners_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='outputs',
        ),
        migrations.AddField(
            model_name='sector',
            name='outcomes',
            field=models.ManyToManyField(related_name='sectors', to='jplaos.NSEDPOutcome'),
        ),
    ]
