# Generated by Django 3.2.3 on 2021-09-06 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0040_auto_20210906_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelineplannedamount',
            name='partner',
        ),
    ]
