# Generated by Django 3.2.3 on 2021-09-06 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0041_remove_pipelineplannedamount_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipelineplannedamount',
            old_name='planed_amount_2021',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='pipelineplannedamount',
            name='planed_amount_2022',
        ),
        migrations.RemoveField(
            model_name='pipelineplannedamount',
            name='planed_amount_2023',
        ),
        migrations.RemoveField(
            model_name='pipelineplannedamount',
            name='planed_amount_2024',
        ),
        migrations.RemoveField(
            model_name='pipelineplannedamount',
            name='planed_amount_2025',
        ),
        migrations.RemoveField(
            model_name='pipelineplannedamount',
            name='planed_amount_2026',
        ),
        migrations.RemoveField(
            model_name='pipelineplannedamount',
            name='planed_amount_2027',
        ),
    ]
