# Generated by Django 3.2.3 on 2021-09-06 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jplaos', '0042_auto_20210906_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_user',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
