# Generated by Django 3.2.3 on 2021-09-06 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0043_alter_partneruser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pipelines',
                                    to='jplaos.partner'),
            preserve_default=False,
        ),
    ]
