# Generated by Django 3.2.3 on 2021-09-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0045_project_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='priorityarea',
            name='outcomes',
            field=models.ManyToManyField(related_name='priority_areas', to='jplaos.NSEDPOutcome'),
        ),
        migrations.AddField(
            model_name='priorityarea',
            name='sdg',
            field=models.ManyToManyField(related_name='priority_areas', to='jplaos.SustainableDevelopmentGoal'),
        ),
    ]
