# Generated by Django 3.2.3 on 2021-09-19 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0046_auto_20210916_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingbyphakhaolaocategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fundingbyphakhaolaocategory',
            name='project',
        ),
        migrations.RemoveField(
            model_name='greensubcategoryfundingallocation',
            name='project',
        ),
        migrations.RemoveField(
            model_name='greensubcategoryfundingallocation',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='FundingByForestPartnershipCategory',
        ),
        migrations.DeleteModel(
            name='FundingByPhakhaoLaoCategory',
        ),
        migrations.DeleteModel(
            name='GreenSubCategoryFundingAllocation',
        ),
    ]
