# Generated by Django 3.2.3 on 2021-09-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0047_auto_20210919_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingbygreencategory',
            name='allocation',
            field=models.IntegerField(verbose_name='Allocation (%)'),
        ),
        migrations.AlterField(
            model_name='partnerfunding',
            name='planed_amount',
            field=models.FloatField(verbose_name='Planned Amount (€)'),
        ),
        migrations.AlterField(
            model_name='pipelineplannedamount',
            name='amount',
            field=models.FloatField(verbose_name='Planned Amounet (€)'),
        ),
    ]
