# Generated by Django 3.2.3 on 2021-09-29 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jplaos', '0048_auto_20210919_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implementingpartnercategory',
            options={'verbose_name': 'Implementing Partner Category',
                     'verbose_name_plural': 'Implementing Partner Categories'},
        ),
    ]
