# Generated by Django 4.2.3 on 2023-07-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0049_alter_implementingpartnercategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='outcomes',
            field=models.ManyToManyField(blank=True, to='jplaos.nsedpoutcome'),
        ),
    ]
