# Generated by Django 4.2.3 on 2023-07-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0051_remove_sector_outcomes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='sdg',
        ),
    ]
