# Generated by Django 4.2.3 on 2023-08-04 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0052_remove_sector_sdg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_cycle', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Programming Cycles',
                'db_table': 'programming_cycle',
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='outcomes',
            field=models.ManyToManyField(blank=True, to='jplaos.nsedpoutcome', verbose_name='NSEDP Outcome'),
        ),
        migrations.AddField(
            model_name='project',
            name='programming_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='jplaos.programmingcycle'),
        ),
    ]
