# Generated by Django 4.2.3 on 2023-09-26 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0053_programmingcycle_alter_project_outcomes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_type', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Funding Type',
                'verbose_name_plural': 'Funding Types',
            },
        ),
        migrations.AlterModelOptions(
            name='pipeline',
            options={'verbose_name': 'Indicative Financial Commitment', 'verbose_name_plural': 'Indicative Financial Commitments'},
        ),
        migrations.AddField(
            model_name='project',
            name='funding_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='jplaos.fundingtype'),
        ),
    ]
