# Generated by Django 4.2.3 on 2023-09-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0054_fundingtype_alter_pipeline_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fundingtype',
            table='funding_type',
        ),
    ]
