# Generated by Django 4.2.3 on 2023-12-06 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jplaos', '0055_alter_fundingtype_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerfunding',
            name='funding_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='jplaos.fundingtype'),
            preserve_default=False,
        ),
    ]
